name: Keep Render Backend Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  ping_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render backend
        run: curl -X GET "https://link-shortner-react-backend.onrender.com"
